# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/user.proto\x12\x04user\"&\n\x13ValidateUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"(\n\x14ValidateUserResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x32T\n\x0bUserService\x12\x45\n\x0cValidateUser\x12\x19.user.ValidateUserRequest\x1a\x1a.user.ValidateUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALIDATEUSERREQUEST']._serialized_start=26
  _globals['_VALIDATEUSERREQUEST']._serialized_end=64
  _globals['_VALIDATEUSERRESPONSE']._serialized_start=66
  _globals['_VALIDATEUSERRESPONSE']._serialized_end=106
  _globals['_USERSERVICE']._serialized_start=108
  _globals['_USERSERVICE']._serialized_end=192
# @@protoc_insertion_point(module_scope)
